//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHero.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.PhotoFaces = new HashSet<PhotoFace>();
        }
    
        public int Id { get; set; }
        public string LocalFileName { get; set; }
        public string HostingSite { get; set; }
        public string WarConflicts { get; set; }
        public string PhotoIdentifier { get; set; }
        public string Description { get; set; }
        public string PhotoUrl { get; set; }
        public string ContentUrl { get; set; }
        public bool IsImageDownloaded { get; set; }
        public bool IsFaceDetected { get; set; }
        public string ErrorText { get; set; }
        public bool HasError { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoFace> PhotoFaces { get; set; }
    }
}
