//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHero.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoFace
    {
        public int Id { get; set; }
        public int PhotoId { get; set; }
        public System.Guid CortanaFaceId { get; set; }
        public Nullable<double> Age { get; set; }
        public string Gender { get; set; }
        public string Glasses { get; set; }
        public Nullable<double> SmileCalculation { get; set; }
        public Nullable<bool> HasSmile { get; set; }
        public int FaceRectangleTop { get; set; }
        public int FaceRectangleLeft { get; set; }
        public int FaceRectangleHeight { get; set; }
        public int FaceRectangleWidth { get; set; }
        public Nullable<System.Guid> FaceGroupId { get; set; }
    
        public virtual Photo Photo { get; set; }
    }
}
